[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_portfolio = "2qGei6swdiMgyXXvNFBuHUypkftbJ5Wy6118B6Y3KmL1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/markoorn/.config/solana/id.json"

[scripts]
test = "node tests/solanaportfolio.js"
