[features]
seeds = false
skip-lint = false
[programs.devnet]
solanaportfolio = "6VrvAT7HaxLE2iww8tViFkkCFGsc2pUVYrwDt6rE5asc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/markoorn/.config/solana/id.json"

[scripts]
test = "node tests/solanaportfolio.js"
